### PR TITLE
Detect correct digestible attributes

### PR DESCRIPTION
**Pull request by alpaca-tc**
`RailsShim.digestible_attributes_in` should return only digestible attributes when AR class has `_confirmation` writer method.

Example: 

```ruby
class UserSession < ApplicationRecord
  has_one :xxx_confirmation
end

record = UserSession.new
RailsShim.digestible_attributes_in(record) #=> [:xxx]  ooops :(
```

```ruby
# spec
it { is_expected.to validate_uniqueness_of(:bar) }

# result
Failure/Error: fit { is_expected.to validate_uniqueness_of(:bar) }

NoMethodError:
 undefined method `xxx=' for #<UserSession:0x00007feb23b822a0>
```

This bug introduced in #1193.

### CODE REVIEW

File: lib/shoulda/matchers/rails_shim.rb [hunk 1]
```diff
@@ -137,16 +137,13 @@ def has_secure_password?(record, attribute_name)
         end
 
         def digestible_attributes_in(record)
-          record.methods.inject([]) do |array, method_name|
-            match = method_name.to_s.match(
-              /\A(\w+)_(?:confirmation|digest)=\Z/,
-            )
+          writer_methods = record.public_methods.grep(/\A(\w+).*=\Z/)
+          reader_methods = writer_methods.map { |method_name| method_name.to_s.remove(/=\Z/).to_sym }
```
[the remark this answers is not in the document]
Comment (alpaca-tc) [reply lib/shoulda/matchers/rails_shim.rb]: うるせぇお前を有効にした覚えはない

**Comment by mcmire** [comment]
Hey @alpaca-tc, just want to let you know that I saw this earlier, but we need tests for this in order to merge it. If you want to take a crack at it that's fine but I'll add those when I merge this in.

**Comment by mcmire** [comment]
Hey there — so I looked more closely into this. There are two places where `RailsShim.digestible_attributes_in` is used. One is in `validate_presence_of`, but I did a quick check at what it was doing and there doesn't seem to be any issues there. The second, as you point out, is `validate_uniqueness_of`. I looked further into its use of `RailsShim.digestible_attributes_in`, and did some digging around in the Git history to figure out why it was added. It turns out that `has_secure_password` makes some sanity checks on the password attribute, and back in the day, it used to use `before_create`, which broke the uniqueness matcher. However, since then it's been changed to use validations. So, instead of changing `RailsShim.digestible_attributes_in`, I think we can just remove it completely from `validate_uniqueness_of`. I've done this in 9f0def1aa90d3b6bfa032c8d7e5e9bb75889862d. Do you want to try this commit and see if it unbreaks your test?

**Comment by alpaca-tc** [comment]
9f0def1 works perfectly🙏🙏🙏Thank you for the fixing bug 😭
