### ISSUE TITLE
Rails 5: belongs_to :class, optional: true 

### ISSUE THREAD

**Issue by stephanngamedev** [thoughtbot/shoulda-matchers#870]
`belongs_to` will now trigger a validation error by default if the association is not present.
We can turn this off on a per-association basis with `optional: true`.
https://github.com/rails/rails/pull/18937

We will need a qualifier for this.

**Comment by mcmire** [comment]
Okay -- do you plan on using `optional: true`? We tend to add qualifiers on an as-needed basis.

**Comment by stephanngamedev** [comment]
Yes. I'm developing a app where a Amiibo may or may not to belongs to Series. ex.: Sonic amiibo belongs to Smash Bros. Series, but Wolf Link amiibo belongs to none.

**Comment by mcmire** [comment]
Cool. I'm not sure when I'll be able to get to this, as I am working on resolving some regressions with the 3.0 release right now, but I would happily take a PR, otherwise I'll get to it at some point down the line. I'll leave this open in the meantime since it's related to Rails 5.

**Comment by thomasbiddle** [comment]
I have a use-case for this as well.

**Comment by leoebrown** [comment]
I also have a use case for this. A food database where most of the foods are not created by users, but users can create foods and 'own' the foods that they create. Workaround: the admin user profile will own foods by default. Please correct me if there's a better workaround or existing solution.

**Comment by stephanngamedev** [comment]
You can use ` belongs_to :user, optional: true` for specific case or just put on application.rb `config.active_record.belongs_to_required_by_default = false` to config all application

**Comment by leoebrown** [comment]
@stephanngamedev I did neither of those things and it seems like I can create foods with user_id: nil no problem--am I missing something? My migration:

```
class AddUserToFoods < ActiveRecord::Migration
  def change
    add_reference :foods, :user, index: true, foreign_key: true
  end
end
```

**Comment by stephanngamedev** [comment]
Are you using Rails 5?

**Comment by leoebrown** [comment]
I am using Rails 4. Sorry, I see this thread is labeled Rails 5. Would your recommendations be necessary in Rails 5?

**Comment by stephanngamedev** [comment]
Yes. My recomendations is to make rails 5 belongs_to behavior like rails 4 belongs_to

**Comment by mcmire** [comment]
@leoebrown Rails 5 changed the behavior of `belongs_to` so that it implicitly adds a presence validation for the association; `optional: true` disables that behavior. But in Rails 4 you don't really have to worry about this. If I remember correctly, if you leave your `*_id` column blank then your association will return nil (this works for both Rails 4 and 5). So you can use the `belongs_to` matcher without having to specify any additional qualifiers.

**Comment by vizcay** [comment]
Hi! there is some progress on this?

I used to have ```validate association, presence: true``` back in Rails 4 to check that the referenced model exists and it was verified by a ***validate_presence_of***. Now, in Rails 5, this is the default behaviour but if I remove the validation in the model to dry it up, the spec now fails because the errors messages diffier ("must exist" vs "can't be blank").

According to the new Rails behaviour, do you think that shoulda-matchers should test this by assigning nil and checking if and error was added? And if a qualifier was passed, the inverse check..

**Comment by xDAGRONx** [comment]
@vizcay for what it's worth, you can get the spec to pass by adding `with_message(:required)` like so:

```
is_expected.to validate_presence_of(association).with_message(:required)
```

**Comment by ybakos** [comment]
Given a Rails 5 model with the association,

    belongs_to :featured_plant, class_name: 'Plant', optional: true

I should be able to test the association with:

    it { is_expected.to belong_to(:featured_plant).class_name('Plant').optional(true) }

to verify that the presence of an associated model is not required.

**Comment by chamnap** [comment]
@ybakos, I tested it doesn't work on `v3.1.1`.

**Comment by lekansogunle** [comment]
We are only testing for validation of the presence of the association ID, what if the given ID is false. And dont want to validate the existence of such association?

**Comment by robbl-as** [comment]
@mcmire @stephanngamedev Isn't that issue resolved by now?

**Comment by Fornacula** [comment]
Doesn't seem to work in version 3.1.2 for I am getting:
` undefined method `optional' for #<Shoulda::Matchers::ActiveRecord::AssociationMatcher`
when I'm doing `it { is_expected.to belong_to(:user).optional(true) }`

**Comment by mcmire** [comment]
Not sure why this issue wasn't closed automatically, but yes, this is resolved by #1058. It'll be available in the next version, or you're feeling adventurous, you can point to the master branch.

**Comment by Akhilesh05** [comment]
@mcmire When will this version be released?
The new code was merged 19th Oct 2017 but is still not present in the latest version!

**Comment by lucascaton** [comment]
Any news on this? Thanks :)

**Comment by namtx** [comment]
```ruby
Failure/Error: it{is_expected.to belong_to(:position).optional true}
     
     NoMethodError:
       undefined method `optional' for #<Shoulda::Matchers::ActiveRecord::AssociationMatcher:0x00000000024649c8>
       Did you mean?  options
```

**Comment by mcmire** [comment]
@namtx @Akhilesh05 @lucascaton We have a pre-release version out now! Try v4.0.0.rc1 to get `optional`.

**Comment by vnbrs** [comment]
In v4.0.0+, the usage is:

```
it { should belong_to(:sender).optional }
```

without the bool argument.
