### ISSUE TITLE
Issue when upgrade to 3.0.1 from 2.8.0 version 

### ISSUE THREAD

**Issue by thomastran** [thoughtbot/shoulda-matchers#852]
When i upgraded the version to 3.0.1 i got this issue, seem that shoulda-matcher was not loaded.  And rspec worked when i rolled-back the gem to 2.8.0 

```  
 Failure/Error: it { should validate_length_of(:phone).is_at_least(10).is_at_most(20) }
     
     NoMethodError:
       undefined method `validate_length_of' for #<RSpec::ExampleGroups::User::Phone:0x007fa6ace1c710>
     # ./spec/models/user_spec.rb:87:in `block (3 levels) in <top (required)>'
```

=================================
Here is my environment
- Ruby 2.2
- Rails 4
- rspec-rails (3.4.0)

**Comment by mcmire** [comment]
I'm not certain, but I'm guessing this has to do with where your test file is located. Have you seen [this section in the README](https://github.com/thoughtbot/shoulda-matchers#availability-of-matchers-in-various-example-groups)?

**Comment by aripollak** [comment]
Or possibly [this section](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md#300) of NEWS?

**Comment by thomastran** [comment]
@aripollak yeahh it is.   I guess it's compatibility issue but don't see that on the latest README. Thx

**Comment by mcmire** [comment]
What did you end up finding out? If it's not in the README, I'm happy to add it.
