### ISSUE TITLE
Undefined method for all shoulda matchers

### ISSUE THREAD

**Issue by jokklan** [thoughtbot/shoulda-matchers#494]
I get this error when i run my specs

```
Failure/Error: it { should validate_presence_of(:body) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_3:0x007f9fad7e2a08>
```

I get this for all shoulda matchers, like `accept_nested_attributes_for`, `validates_uniqueness_of` etc.

This started happening after i upgraded to shoulda 2.6.0 from 2.5.0. Any idea why this is happening?
