### ISSUE TITLE
Error with have_many() with .class_name

### ISSUE THREAD

**Issue by diegorv** [thoughtbot/shoulda-matchers#647]
```ruby
require 'spec_helper'

describe Client::Client, :type => :model do
  # -------------------------------------------------------------------------------------

  context "associations" do
    it { should have_many(:companies)                                 }
    it { should have_many(:contracts).class_name(Contract::Contract)  }
  end
end
```

```ruby
Failures:

  1) Client::Client associations should have many contracts class_name => Contract::Contract
     Failure/Error: it { should have_many(:contracts).class_name(Contract::Contract)  }
     NoMethodError:
       undefined method `split' for #<Class:0x007fe6028c5f60>
     # ./spec/models/clients/client_spec.rb:8:in `block (3 levels) in <top (required)>'
```

Versions: shoulda-matchers (2.8.0) - rails (4.2.0)
Ruby: 2.2.0

**Comment by maurogeorge** [comment]
@diegorv could you please try pass the `class_name` as a string. Like:

```ruby
it { should have_many(:contracts).class_name('Contract::Contract')  }
```
In the docs accept only strings http://matchers.shoulda.io/docs/v2.8.0/Shoulda/Matchers/ActiveRecord.html#have_many-instance_method

**Comment by diegorv** [comment]
Yep, my bad.

Without string works fine in 2.7.0, but not anymore in 2.8.0

Thanks @maurogeorge

**Comment by mcmire** [comment]
Does the `:class_name` option for `has_many` (the association) take a constant as the class, too? I wasn't aware that it did...
