### ISSUE TITLE
1.5.5 breaks validate_numericailty_of matcher

### ISSUE THREAD

**Issue by agrobbin** [thoughtbot/shoulda-matchers#277]
When I upgraded to 1.5.5, I re-ran my test suite as you indicated since certain tests may now fail, and indeed I am getting an error for previously passing tests:

```
  1) Event 
     Failure/Error: it { should_not validate_numericality_of(:weight) }
     NoMethodError:
       undefined method `negative_failure_message' for #<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007f88a204a308>
     # ./spec/models/event_spec.rb:13:in `block (2 levels) in <top (required)>'

  2) Event 
     Failure/Error: it { should_not validate_numericality_of(:points_possible) }
     NoMethodError:
       undefined method `negative_failure_message' for #<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007f88a0cf4718>
     # ./spec/models/event_spec.rb:12:in `block (2 levels) in <top (required)>'

  3) Event when the event is an assignment validations 
     Failure/Error: it { should_not validate_numericality_of(:weight) }
     NoMethodError:
       undefined method `negative_failure_message' for #<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007f88a0aef828>
     # ./spec/models/event_spec.rb:75:in `block (4 levels) in <top (required)>'
```

I've bisected this back to a change introduced in 5da9f52134f1103cbedbaf00b411a3c96fc7cd40, hopefully that helps track down the problem!
