### ISSUE TITLE
NoMethodError: undefined method `object_class' for ActiveRecord::Store::IndifferentCoder

### ISSUE THREAD

**Issue by coorasse** [thoughtbot/shoulda-matchers#1234]
The latest release 4.1.1 performs a call to `object_class` in `validate_presence_of_matcher.rb:318`, raising an error 
```
NoMethodError: undefined method `object_class' for #<ActiveRecord::Store::IndifferentCoder:0x00007fa7c76f31e8>
```

**Comment by mcmire** [comment]
Hey @coorasse, thanks for the report. What does your model look like so that I can reproduce this?

**Comment by dark-panda** [comment]
I'm experiencing this too. The code is effectively:

```ruby
module HashWithIndifferentAccessSerializer
  def self.dump(value)
    value
  end

  def self.load(value)
    value.try(:with_indifferent_access) || value
  end
end

create_table :foos do |t|
  t.references :resource, type: :uuid, polymorphic: true, index: true, null: false
  t.jsonb :data
  t.timestamps
end

class Foo < ApplicationModel
  serialize :data, HashWithIndifferentAccessSerializer
end

RSpec.describe Recaptcha, type: :model do
  describe 'validations' do
    it { is_expected.to validate_presence_of(:data) }
  end
end
```

**Comment by tnandate** [comment]
I'm experiencing a similar problem too.
```
create_table :hoges do |t|
  t.text :data, null: false
  t.timestamps
end

class Hoge < ApplicationRecord
  serialize :data, JSON

  validates :data, presence: true
end

RSpec.describe Hoge, type: :model do
  it { is_expected.to validate_presence_of(:data) }
end
```

raising an error
```
NoMethodError:
       undefined method `object_class' for ActiveRecord::Coders::JSON:Class
       Did you mean?  object_id
```

**Comment by stas** [comment]
This was introduced in https://github.com/thoughtbot/shoulda-matchers/commit/b3025dc9a52958a86406183472272ef2b8064085

Any model attribute using the [`#serialize`](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize) will fail.

Current workaround is to downgrade to the previous version.

**Comment by mcmire** [comment]
Thanks for the reports — I'll make this a priority and try to get a fix out for this soon.

**Comment by mcmire** [comment]
@coorasse @dark-panda @tnandate @stas I have a branch that should fix this issue. Can you temporarily switch to the `fix-presence-with-custom-serializer` branch in your Gemfile and see if that makes your tests pass?

**Comment by meric426** [comment]
> @coorasse @dark-panda @tnandate @stas I have a branch that should fix this issue. Can you temporarily switch to the `fix-presence-with-custom-serializer` branch in your Gemfile and see if that makes your tests pass?

This solved the issue for us. Merge away :)

**Comment by coorasse** [comment]
The issue is solved for me using the branch `fix-presence-with-custom-serializer`

**Comment by tnandate** [comment]
I confirmed that my test passed.

**Comment by mcmire** [comment]
This should now be fixed in 4.1.2!
