### ISSUE TITLE
undefined method `validate_numericality_of' 

### ISSUE THREAD

**Issue by 8vius** [thoughtbot/shoulda-matchers#881]
I'm getting this error when running some specs 

```
Failure/Error: should validate_numericality_of(:minutes_worked).
     NoMethodError:
       undefined method `validate_numericality_of' for #<RSpec::ExampleGroups::Service:0x007f9aedaec380>
```

My shoulda-matchers version is 3.1.0. Any idea what might be the issue?

**Comment by mcmire** [comment]
Did you follow the [instructions in the README](https://github.com/thoughtbot/shoulda-matchers#configuration) to configure the gem?

**Comment by 8vius** [comment]
Yeah, I found the error. The test was defined as a `feature` spec and from what I saw that method only works in model specs. Thanks!

**Comment by mcmire** [comment]
That makes sense. Glad you figured it out :)

**Comment by trushkevich** [comment]
I face this error after upgrading to 3.1.1, but when I downgrade  back to 2.8.0 the error goes away.
