### ISSUE TITLE
Failing test on primary: true option

### ISSUE THREAD

**Issue by abitdodgy** [thoughtbot/shoulda-matchers#639]
The following test is failing with an error:

```
  1) Error:                                                                                                                                                                                                                                          
UserTest#test_: User should have db column named id of type integer of primary true. :                                                                                                                                                               
NoMethodError: undefined method `primary' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x000000039837c8> 
```

```ruby
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  should have_db_column(:id).of_type(:integer).with_options(primary: true)
end
```

Removing the `with_options` method the test behaves as expected.

I'm using Ruby 2.2.0 and Rails 4.2. 

Shoulda versions:

shoulda (3.5.0)                                                                                                                                                                                                                                      
shoulda-context (1.2.1)                                                                                                                                                                                                                              
shoulda-matchers (2.7.0)

**Comment by mcmire** [comment]
Thanks for the report, I'll take a look.

**Comment by mcmire** [comment]
@abitdodgy The tests now run against Postgres, and I am not seeing this issue. Do you mind re-running your tests against master and see if you are still getting this?

**Comment by mcmire** [comment]
@abitdodgy Actually, does this work on 2.8.0?

**Comment by abitdodgy** [comment]
@mcmire I'll be able to test this when I get into the office tomorrow afternoon. Cheers for the heads up and the fix. I'll post back.

**Comment by seanot** [comment]
'Late to the party... I ran into a similar issue with "validate_uniqueness_of" with v2.6.0 this afternoon. 
```
1) StripeWebHook should require case sensitive unique value for stripe_id
     Failure/Error: it { is_expected.to validate_uniqueness_of(:stripe_id) }
     NoMethodError:
       undefined method `primary' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f99e5a3eb80>
```
Upgraded to v2.8.0 and the error no longer occurs. Tried v3.0.0alpha and every shoulda-matcher-based  test failed. I'm running Ruby 2.2 and Rails 4.2.

I'm happy running 2.8.0. 'Appreciate all of your efforts to keep this great gem current!

**Comment by abitdodgy** [comment]
@mcmire I can confirm that this is now fixed. Sorry about the delay in reporting back. Thank you!
