### ISSUE TITLE
undefined method `join' for nil:NilClass in capybara

### ISSUE THREAD

**Issue by cschramm** [thoughtbot/shoulda-matchers#259]
After updating from 1.4.2 to 1.5.1 (couldn't use 1.5.0 due to #248), I get:

```
undefined method `join' for nil:NilClass (NoMethodError)
/var/lib/gems/1.9.1/gems/capybara-2.0.2/lib/capybara/rails.rb:15:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/rspec-rails-2.13.0/lib/rspec/rails/vendor/capybara.rb:7:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/rspec-rails-2.13.0/lib/rspec/rails.rb:16:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/shoulda-matchers-1.5.1/lib/shoulda/matchers/integrations/rspec.rb:2:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/shoulda-matchers-1.5.1/lib/shoulda/matchers.rb:5:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:213:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.0.0.beta1/lib/active_support/dependencies.rb:228:in `require'
/var/lib/gems/1.9.1/gems/shoulda-matchers-1.5.1/lib/shoulda-matchers.rb:1:in `<top (required)>'
```

Bourne was updated from 1.1.2 to 1.4.0 and mocha from 0.10.5 to 0.13.3. I didn't touch capybara, so it must be related to one of those gems. Maybe somethin similar to blowmage/minitest-rails-capybara#1?
