### ISSUE TITLE
validate_inclusion_of doesn't work with 2.6.2

### ISSUE THREAD

**Issue by jasonnoble** [thoughtbot/shoulda-matchers#558]
https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb says we should use the following:

it { should validate_inclusion_of(:state).in_range(1..5) }

But I get an error:

  1) Car
     Failure/Error: it { should validate_inclusion_of(:year).in_range(1769..2014) }
     NoMethodError:
       undefined method `validate_inclusion_of' for #<RSpec::ExampleGroups::Car:0x007f8670c1d380>
     # ./spec/models/car_spec.rb:11:in`block (2 levels) in <top (required)>'

Changing it to the "old" ensure_inclusion_of fixed the issue.

Maybe a new version of the gem needs to be released?
