### ISSUE TITLE
undefined method `does_not_match?' for (...) OnlyIntegerMatcher

### ISSUE THREAD

**Issue by easybills-admin** [thoughtbot/shoulda-matchers#1195]
Hi there! 👋

I've found an issue when upgrading from version 3.x to 4.0.1.

The following spec used to pass:

```ruby
# app/models/account.rb
class Account < ApplicationRecord
  # empty
end

# spec/models/account_spec.rb
RSpec.describe Account, type: :model do
  it do
    is_expected.not_to validate_numericality_of(:initial_amount_cents)
      .is_greater_than_or_equal_to(0).only_integer
  end
end
```

Now it fails with the following error:

```ruby
1) Account should not validate that :initial_amount_cents looks like an integer greater than or equal to 0
   Failure/Error:
     is_expected.not_to validate_numericality_of(:initial_amount_cents)
       .is_greater_than_or_equal_to(0).only_integer

   NoMethodError:
     undefined method `does_not_match?' for #<Shoulda::Matchers::ActiveModel::NumericalityMatchers::OnlyIntegerMatcher:0x00007f99519d1d80>
   # (...)/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:577:in `block in first_submatcher_that_fails_to_not_match'
   # (...)/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:576:in `each'
   # (...)/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:576:in `detect'
   # (...)/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:576:in `first_submatcher_that_fails_to_not_match'
   # (...)/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb:420:in `does_not_match?'
   # ./spec/models/account_spec.rb:3:in `block (2 levels) in <main>'
```

---

I declare this validation dynamically, depending on some conditions, that's why I sent the above example with an empty model.

Thank you!

---

My current stack:

* Ruby 2.6.2
* Rails 5.2.2.1
* rspec-rails 3.8.2
* shoulda-matchers 4.0.1

**Comment by mcmire** [comment]
Hey @easybills-admin. Thanks for reporting this. It's very possible we are missing tests for the negative case here, otherwise we would have caught this! We'll make sure to include a fix for this in the next release.

**Comment by mcmire** [comment]
This should be fixed now.
