### ISSUE TITLE
belong_to sets association to nil, causing a failure in validations

### ISSUE THREAD

**Issue by stanhu** [thoughtbot/shoulda-matchers#1209]
In GitLab, we have the following definitions:

```ruby
class MergeRequest < ActiveRecord::Base
  belongs_to :target_project, class_name: "Project"
  belongs_to :source_project, class_name: "Project"

  validate :validate_branches

  def validate_branches
    if opened?
      similar_mrs = target_project
	.merge_requests
        .where(source_branch: source_branch, target_branch: target_branch)
        .where(source_project_id: source_project&.id)
        .opened
    <snip>
```

In the spec we have:

```ruby
describe MergeRequest do
  subject { create(:merge_request) }

  it { is_expected.to belong_to(:target_project).class_name('Project') }
end
```

After upgrading from shoulda-matchers 3.1.2 to 4.0.1, this fails:

```ruby
Failures:

  1) MergeRequest associations should belong to target_project class_name => Project required:
     Failure/Error:
       similar_mrs = target_project
         .merge_requests
         .where(source_branch: source_branch, target_branch: target_branch)
         .where(source_project_id: source_project&.id)
         .opened

     NoMethodError:
       undefined method `merge_requests' for nil:NilClass
     # ./app/models/merge_request.rb:591:in `validate_branches'
     # ./spec/models/merge_request_spec.rb:13:in `block (3 levels) in <top (required)>'
```

It seems the problem occurs because `AttributeSetter` in https://github.com/thoughtbot/shoulda-matchers/blob/bf7ea9a3af3ff09f1a3563ea127fa6ea16084a8a/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb#L83 is setting `target_project` to `nil`, so when the validation runs later the association no longer exists. Adding a debugger shows that before the call to `AllowValueMatcher#run`, the `target_project` exists, but afterwards it's `nil.` The backtrace:

```
/Users/stanhu/gdk/gitlab/app/models/merge_request.rb:589:in `validate_branches'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `catch'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:130:in `run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-5.1.7/lib/active_model/validations.rb:405:in `run_validations!'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-5.1.7/lib/active_model/validations/callbacks.rb:114:in `block in run_validations!'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-activemodel-0.5.1/lib/state_machines/integrations/active_model.rb:400:in `block in around_validation'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:150:in `block in run_actions'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:170:in `catch_exceptions'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:148:in `run_actions'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:133:in `run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:212:in `run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:63:in `catch'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:63:in `block in perform'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:186:in `within_transaction'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-0.5.0/lib/state_machines/transition_collection.rb:62:in `perform'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/state_machines-activemodel-0.5.1/lib/state_machines/integrations/active_model.rb:400:in `around_validation'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-5.1.7/lib/active_model/validations/callbacks.rb:114:in `run_validations!'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activemodel-5.1.7/lib/active_model/validations.rb:335:in `valid?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/validations.rb:65:in `valid?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:96:in `perform_validation'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:89:in `validation_result'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:85:in `validation_error_messages'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:64:in `messages'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:25:in `has_messages?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:55:in `messages_match?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/validator.rb:21:in `call'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:42:in `does_not_match?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `each'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `detect'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `first_failing'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `public_send'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:534:in `run'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:395:in `matches?'
/Users/stanhu/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shoulda-matchers-4.0.1/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:36:in `does_not_match?'
```

Should `belong_to` be mutating the subject that it's testing?

**Comment by mcmire** [comment]
Yes, this is intentional. Starting with Rails 5, `belongs_to` now adds a presence validation to the association, and so as of shoulda-matchers 4.0.0 the `belong_to` matcher follows suit and tests that this validation is there by setting the association to nil and asserting that there are validation errors. So it seems like the matcher has revealed a potential issue in your validation method. You may wish to check for whether `target_project` is nil before trying to call something on it first.

**Comment by stanhu** [comment]
@mcmire Ok, thanks! I was thrown off because we already have these validations:

```ruby
  validates :source_project, presence: true, unless: [:allow_broken, :importing?, :closed_without_fork?]
  validates :target_project, presence: true
```

But I suppose we can't assume that these are called before this validation?

Thanks for your help!

**Comment by mcmire** [comment]
Ah, okay. Yes, if you've placed these before the `validate` line, then they should be getting called beforehand. Although, if a validation fails, it's not going to prevent the other ones from running — ActiveRecord will run all of them.

That said, since you have custom validations, it might be more helpful in this case to tack `.without_validating_presence` onto the end of your `belong_to` matcher — that will skip the validation and let you test it separately if need be.
